name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Test
        run: pytest
      - name: Build Image
        run: pack build <your-registry>/python-oops-app --builder paketobuildpacks/builder:base
